name: gendiff testing
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: get repository
        uses: actions/checkout@v3
      - name: install dependencies
        run: make install
      - name: lint
        run: make lint
      - name: test
        run: make test
      - name: coverage
        run: make coverage
      - name: publish test coverage
        uses: paambaati/codeclimate-action@v5.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.TEST_REPORTER_ID }}
